# Generated by Django 3.0.6 on 2020-05-23 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='last_measurement',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='last_measurement_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
