# Generated by Django 3.0.6 on 2020-05-24 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0002_auto_20200523_0133'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scale',
            old_name='associated_item',
            new_name='item',
        ),
        migrations.RenameField(
            model_name='scale',
            old_name='associated_site',
            new_name='site',
        ),
    ]
