# Generated by Django 3.0.6 on 2020-05-24 23:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0003_auto_20200524_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='associated_site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory_management.Site'),
        ),
    ]
