# Generated by Django 3.0.6 on 2020-05-24 23:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0004_auto_20200524_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scale',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scales', to='inventory_management.InventoryItem'),
        ),
        migrations.AlterField(
            model_name='scale',
            name='site',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scales', to='inventory_management.Site'),
        ),
    ]
