# Generated by Django 3.0.6 on 2020-06-12 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0007_auto_20200610_2037'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventoryitem',
            old_name='associated_site',
            new_name='site',
        ),
    ]
