# Generated by Django 3.0.6 on 2020-06-17 14:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0009_auto_20200616_0111'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
