# Generated by Django 3.0.6 on 2020-06-29 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0010_measurement_timestamp'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Measurement',
            new_name='ScaleReading',
        ),
    ]
