# Generated by Django 3.0.6 on 2020-06-29 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0011_auto_20200629_1726'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemMeasurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='inventory_management.InventoryItem')),
            ],
        ),
    ]
