# Generated by Django 3.0.6 on 2020-06-29 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0012_itemmeasurement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryitem',
            name='last_measurement',
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='last_measurement_timestamp',
        ),
    ]
