# Generated by Django 3.0.6 on 2020-08-06 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0013_auto_20200629_1737'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemmeasurement',
            name='item',
        ),
        migrations.RemoveField(
            model_name='scale',
            name='item',
        ),
        migrations.CreateModel(
            name='ItemStocking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stockings', to='inventory_management.InventoryItem')),
            ],
        ),
        migrations.AddField(
            model_name='itemmeasurement',
            name='stocking',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='inventory_management.ItemStocking'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scale',
            name='stocking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scales', to='inventory_management.ItemStocking'),
        ),
    ]
